trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .changeset/*.md

pool:
  vmImage: "ubuntu-latest"
variables:
  - group: common-vg
jobs:
  - job: Release_new_version
    displayName: "Release new version"
    # container:
    #     image: node:16
    steps:
      - task: NodeTool@0
        displayName: "Install Node.js"
        inputs:
          versionSpec: "16.x"

      - script: |
          ls -la
          pwd
          rm -rf ./*
          git clone https://x-token-auth:$(asma-core-ui-bitbucket-token)@bitbucket.org/carasent/asma-core-ui.git .
          git status
          # git fetch origin master:master
          # git checkout master
          # git clone https://x-token-auth:$(asma-core-ui-bitbucket-token)@bitbucket.org/carasent/asma-core-ui.git
          # cd asma-core-ui
          # mv asma-core-ui/* .
          # git switch --detach master

          # # Rename package.json
          # mv package.json package_old.json

          # # Install Changeset CLI
          # npm install @changesets/cli --no-save --no-package-lock

          # # Rename package_old.json to package.json
          # mv package_old.json package.json

          # # Show changeset status
          # npm run changeset:status

          # # Bump version and create changelog with Changeset
          # #npx -q @changesets/cli -- version
          # npm run changeset:version

          # # Commit changes
          # VERSION=$(npm run version --silent)
          # LASTCOMMIT=$(git rev-parse --short HEAD)
          # git config user.email "712020:f4b4d0c3-fb46-4b7b-b851-f6509a6ab9bc@bots.bitbucket.org"
          # git config --global user.name "npx changeset"
          # git add .
          # git commit -m "[skip ci] Version - ${VERSION}"
          # git -c http.extraheader="AUTHORIZATION: bearer $(asma-core-ui-bitbucket-token)" push origin master
        displayName: "Bump version and create changelog"

      # - script: |
      #     yarn install
      #     yarn build

      #     # Log in to npm
      #     echo "//registry.npmjs.org/:_authToken=$(npm-token)" > .npmrc

      #     # Publish the package using Changesets
      #     #npx -q @changesets/cli publish
      #     npm run changeset:publish
      #   displayName: "Publish package"
